### ISSUE TITLE
wildcard not working - reported in reddit

### ISSUE THREAD

**Issue by adireddy** [adireddy/waudsprite#1]
This looked great and perfect for my project so I started messing around with it and soon found that WaudSprite just doesn't work, and was last updated two months ago. It seem to stall on a fs.exists() check with a wildcard filename, as is in the examples and without which WaudSprite is utterly pointless.

Issue reported in reddit:

https://www.reddit.com/r/javascript/comments/4xtul7/waudjs_web_audio_library_with_html5_audio_fallback/

**Comment by adireddy** [comment]
I don't have a GitHub account, sorry. But Win10/64, tried many different commands, a simple waudsprite *.wav fails (in a dir with .wavs) with

```
{ msg: 'File does not exist', file: '*.wav' }
error:  Error: Error adding file
    at C:\Users\MyName\AppData\Roaming\npm\node_modules\waudsprite\waudsprite.js:247:33
    at C:\Users\MyName\AppData\Roaming\npm\node_modules\waudsprite\node_modules\async\lib\async.js:148:21
    at C:\Users\MyName\AppData\Roaming\npm\node_modules\waudsprite\waudsprite.js:223:28
    at C:\Users\MyName\AppData\Roaming\npm\node_modules\waudsprite\waudsprite.js:105:17
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

Waudbase64 works fine, presumably because it takes a folder instead of a wildcard, so that would pass a fs.exists().

**Comment by adireddy** [comment]
It works sometimes if I pass ./_.mp3, but not a subfolder (like sounds/_.mp3 or ./sounds/*.mp3). It also dislikes the backslash directory separator, which I can live with. Logging folder in getRecursiveFiles() shows the argument to be an empty string in this case.
It seems I was able to fix it with

```
[-] var filesList = files[0].split("/");
[+] var filesList = files[0].split(/[\/\\]/);
```

but haven't tested beyond my few commands. I suspect the '/' split was causing problems when an OS call returned a backslash-separated path.
